# Generated by Django 2.0.3 on 2019-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fylehome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.CharField(max_length=500),
        ),
    ]
